DROP TABLE IF EXISTS public.ft_machine CASCADE;
-- Table: ft_machine
CREATE TABLE public.ft_machine (
    name text PRIMARY KEY,
    model text,
    oem text,
    sn text,
    type text,
    esn text,
    section_break_4 text,
    column_break_7 text,
    gearbox text,
    section_break_10 text,
    notes text,
    fleet_no text,
    location text,
    region text,
    supplied text,
    warranty_details_section text,
    handover_date timestamp with time zone,
    expiry_date timestamp with time zone,
    column_break_19 text,
    warranty_hours numeric,
    hmr_section text,
    starting_hmr numeric,
    column_break_23 text,
    current_hmr numeric,
    service_details_section text,
    service_interval_hours numeric,
    column_break_27 text,
    last_service_date timestamp with time zone,
    last_service_hmr numeric,
    next_service_hmr numeric,
    initial_service_type numeric,
    warranty_status text,
    service_obligation text,
    initial_service_section text,
    track_initial_service text,
    column_break_37 text,
    initial_service_status text,
    customer text,
    hours_remaining_to_service numeric,
    last_hmr_date timestamp with time zone,
    fleetrack_managed text,
    section_break_2 text,
    colb1 text,
    colb2 text,
    colbr3 text,
    colbr4 text,
    colbr6 text,
    cb1 text,
    cb2 text,
    has_telematics_device text,
    column_break_32 text,
    column_break_47 text,
    column_break_49 text,
    column_break_34 text,
    last_hmr_log text,
    days_since_last_hmr integer,
    column_break_38 text,
    column_break_54 text,
    column_break_44 text,
    column_break_24 text,
    warranty_type text,
    chassis_number text,
    epr_entry_date timestamp with time zone,
    engine_type text,
    warranty_period numeric,
    cbbb2 text,
    mxg_fleet_no text,
    colbr_nre_fleet text,
    section_break_57 text,
    col_br_nst text,
    next_service_type numeric,
    col_br_service_hdr text,
    last_service_type numeric,
    cbroemreg text,
    oem_registered text,
    library_section text,
    filters_list text,
    compatible_get text,
    pdi_checklist text,
    lube_types text,
    belt_dimensions text,
    hyd_filters_dimensions text,
    equipment_information_form text,
    wty_certificate text,
    nei_checklist text,
    column_break_81 text,
    column_break_83 text,
    machine_picture text,
    machine_data_plate text,
    engine_data_plate text,
    supplier text,
    misc_files text,
    madr_section text,
    track_components text,
    rpc_list text,
    parts_manuals text,
    parts_manuals_2 text,
    parts_manuals_3 text,
    operating_weight numeric,
    bin_capacity numeric,
    standard_fuel_consumption numeric,
    tyre_size text,
    canbus_enabled text,
    unique_attachments_fitted integer,
    telematics_section text,
    telematics_device text,
    column_break_yztmf text,
    telematics_device_sn text,
    sim_card text,
    enabled_parameters text,
    service_guide_section text,
    standard_service_configuration text,
    btn_view_unique_attachments text,
    mobility text,
    under_carriage_section text,
    chain_make text,
    column_break_gwqvk text,
    chain_length numeric,
    column_break_jociq text,
    chain_width numeric,
    sprokects_section text,
    sproket_lhs_teeth integer,
    sproket_lhs_holes integer,
    column_break_guec2 text,
    sproket_rhs_teeth integer,
    sproket_rhs_holes integer,
    other_uc_info text,
    get_components_section text,
    get_components text,
    fb_section text,
    filters_and_belts text,
    customer_file_section text,
    machine_welcome_report_status text,
    column_break_duu5t text,
    column_break_4ctjf text,
    prepare_welcome_report text,
    btn_prepare_machine_welcome_report text,
    total_running_hours numeric,
    working_voltage numeric,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.ft_machine ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to ft_machine" ON public.ft_machine FOR ALL USING (true) WITH CHECK (true);

DROP TABLE IF EXISTS public.ft_breakdown_log CASCADE;
-- Table: ft_breakdown_log
CREATE TABLE public.ft_breakdown_log (
    name text PRIMARY KEY,
    machine text,
    column_break_2 text,
    oem text,
    customer text,
    breakdown_date timestamp with time zone,
    location text,
    breakdown_details_section text,
    column_break_8 text,
    description text,
    status text,
    days_on_bd integer,
    end_date timestamp with time zone,
    model text,
    fleetrack_managed text,
    warranty_status text,
    parts_eta timestamp with time zone,
    ted timestamp with time zone,
    red timestamp with time zone,
    fsb text,
    resp text,
    section_break_19 text,
    last_col_br_oeta text,
    section_break_17 text,
    dobd_col_br text,
    oeta_col_br text,
    out_eta timestamp with time zone,
    section_break_27 text,
    on_hold integer,
    ted_status text,
    bd_duration integer,
    category text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);
ALTER TABLE public.ft_breakdown_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all access to ft_breakdown_log" ON public.ft_breakdown_log FOR ALL USING (true) WITH CHECK (true);
