DROP TABLE IF EXISTS public."frappe_fmb_report_machine";
DROP TABLE IF EXISTS public."frappe_quotation";

CREATE TABLE IF NOT EXISTS public."frappe_fmb_report_machine" (
  "name" text PRIMARY KEY,
  "item" text,
  "qty" bigint,
  "parent" text,
  "parentfield" text,
  "parenttype" text,
  "notes" text,
  "target_handover_date" date,
  "revised_handover_date" date,
  "serial_no" text,
  "actual_handover_date" date,
  "internal_notes" text,
  "images_one" text,
  "image_two" text,
  "committed_lead_time" text
);
ALTER TABLE public."frappe_fmb_report_machine" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public."frappe_quotation" (
  "name" text PRIMARY KEY,
  "workflow_state" text,
  "title" text,
  "naming_series" text,
  "quotation_to" text,
  "party_name" text,
  "customer_name" text,
  "custom_delivery" text,
  "transaction_date" date,
  "valid_till" date,
  "custom_bank_account" text,
  "custom_pfi_checked" bigint,
  "custom_additional_notes" text,
  "custom_account_name" text,
  "order_type" text,
  "company" text,
  "custom_sales_person" text,
  "custom_bank" text,
  "custom_bank_account_no" text,
  "custom_branch" text,
  "custom_branch_code" text,
  "amended_from" text,
  "currency" text,
  "conversion_rate" bigint,
  "selling_price_list" text,
  "price_list_currency" text,
  "plc_conversion_rate" bigint,
  "ignore_pricing_rule" bigint,
  "scan_barcode" text,
  "total_qty" bigint,
  "total_net_weight" bigint,
  "base_total" double precision,
  "base_net_total" double precision,
  "total" double precision,
  "net_total" double precision,
  "tax_category" text,
  "taxes_and_charges" text,
  "shipping_rule" text,
  "incoterm" text,
  "named_place" text,
  "base_total_taxes_and_charges" bigint,
  "total_taxes_and_charges" bigint,
  "base_grand_total" double precision,
  "base_rounding_adjustment" bigint,
  "base_rounded_total" bigint,
  "base_in_words" text,
  "grand_total" double precision,
  "rounding_adjustment" bigint,
  "rounded_total" bigint,
  "disable_rounded_total" bigint,
  "in_words" text,
  "apply_discount_on" text,
  "base_discount_amount" bigint,
  "coupon_code" text,
  "additional_discount_percentage" bigint,
  "discount_amount" bigint,
  "referral_sales_partner" text,
  "other_charges_calculation" text,
  "customer_address" text,
  "address_display" text,
  "contact_person" text,
  "contact_display" text,
  "contact_mobile" text,
  "contact_email" text,
  "shipping_address_name" text,
  "shipping_address" text,
  "company_address" text,
  "company_contact_person" text,
  "company_address_display" text,
  "payment_terms_template" text,
  "tc_name" text,
  "terms" text,
  "auto_repeat" text,
  "letter_head" text,
  "group_same_items" bigint,
  "select_print_heading" text,
  "language" text,
  "order_lost_reason" text,
  "status" text,
  "customer_group" text,
  "territory" text,
  "campaign" text,
  "source" text,
  "opportunity" text,
  "supplier_quotation" text,
  "enq_det" text,
  "custom_next_follow_up_date" text,
  "custom_follow_up_status" text,
  "custom_lead_owner" text
);
ALTER TABLE public."frappe_quotation" ENABLE ROW LEVEL SECURITY;


