-- ==============================================================================
-- STEP 2b: Apply RLS Performance Optimizations
-- ==============================================================================
-- Copy this entire file and run it in your Supabase SQL Editor.
-- Because these are standard ALTER POLICY statements (not concurrent indexes),
-- you can run them all at once!

ALTER POLICY "Users can update their own listings" ON public.listings USING (((select auth.uid()) = user_id)) WITH CHECK (((select auth.uid()) = user_id));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_bd_category USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_customer USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_defect_category USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "service_log_all" ON public.ft_service_log USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Public full access" ON public.temp_otps USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable update access for all users" ON public.omnis_tracking_orders USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_sick_notes" ON public.omnis_sick_notes USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_consultations" ON public.omnis_consultations USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_inventory" ON public.omnis_inventory USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_dispensations" ON public.omnis_dispensations USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_appointments" ON public.omnis_appointments USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_salestrack_notifications" ON public.omnis_salestrack_notifications USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow authenticated write on omnis_app_settings" ON public.omnis_app_settings USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow authenticated update to email configs" ON public.email_notification_configs USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow full access to authenticated users on cdv_logs" ON public.cdv_logs USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.product_pricing USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_defect_category" ON public.ft_defect_category USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.payment_installments USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.customer_credit_profiles USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.payment_deals USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_breakdown_log" ON public.ft_breakdown_log USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.fmb_reports USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.order_machines USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.psv_logs USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.order_contacts USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.psv_attachments USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_service_report" ON public.ft_service_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_service_plan" ON public.ft_service_plan USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow full access to authenticated users on cdv_schedules" ON public.cdv_schedules USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow full access to authenticated users on cdv_attachments" ON public.cdv_attachments USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow full access to authenticated users on newsletters" ON public.newsletters USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "auth_all_ft_jc" ON public.ft_job_card USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "auth_all_ft_jci" ON public.ft_job_card_item USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "auth_all_ft_breakdown" ON public.ft_breakdown USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "auth_all_ft_bm" ON public.ft_breakdown_machine USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "auth_all_ft_hmr" ON public.ft_hmr_log USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_location" ON public.ft_location USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_customer" ON public.ft_customer USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_region" ON public.ft_region USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_machine_model" ON public.ft_machine_model USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_machine_oem" ON public.ft_machine_oem USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_machine_type" ON public.ft_machine_type USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_technician" ON public.ft_technician USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_bd_category" ON public.ft_bd_category USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated users" ON public.aftersales_handover USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "auth_all_ft_isr" ON public.ft_isr USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_custom_docperm USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_field_service_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_defect_description USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_field_service_plan USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_get_component USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_image_gallery USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_inspection_checklist_template USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_job_card USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_jrv USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_location USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_component USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_condition_assessment USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_failure USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_model USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_named_component USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_oem USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_service_guide USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_service_item USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_supplier USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_type USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_machine_welcome_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_maintenance_warning_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_monthly_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_region USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_sec_component USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_sec_repair USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_service_bulletin USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_technician_efficiency_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_technician_hour_log USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_telematics_device USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_telematics_parameter USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_tyre_size USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_warranty_claim USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_weekly_maintenance_warning_report USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_number_card USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_onboarding_step USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_scheduled_job_type USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_sec_item USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_sec_repair_log_entry USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_alert USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_jrv_detailed_description USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all for authenticated" ON public.frappe_ft_jrv_description USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable update for all users" ON public.ft_operator_training USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable update for all users" ON public.ft_operator_certificates USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable all access for authenticated users" ON public.omnis_sales_persons USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all on omnis_quote_lifecycle" ON public.omnis_quote_lifecycle USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all update access to training_progress" ON public.training_progress USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable full access for omnis_patients" ON public.omnis_patients USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all actions for stock_contracts" ON public.stock_contracts USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow authenticated users to update stock_company_mappings" ON public.stock_company_mappings USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow full access on campaign_recipients" ON public.campaign_recipients USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable update for authenticated users" ON public.ft_service_logs USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow authenticated update to ft_technicians" ON public.ft_technicians USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Enable update access for all users" ON public.ft_defect USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow authenticated update to ft_technician_hour_log" ON public.ft_technician_hour_log USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow all access to ft_machine" ON public.ft_machine USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
ALTER POLICY "Allow update for authenticated users" ON public.ft_breakdown_logs USING (((select auth.uid()) IS NOT NULL)) WITH CHECK (((select auth.uid()) IS NOT NULL));
